name: Update packages

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update packages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          set -x
          wget "https://github.com/$GITHUB_REPOSITORY/releases/latest/download/komac"
          chmod +x komac
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          python3 main.py
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update packages [$GITHUB_RUN_NUMBER]"
            git push
          fi
